"use client";

import { useState } from "react";
import type { Insights } from "@/lib/types";

/** Requests and displays the assistant's personalized recommendations. */
export default function InsightsPanel() {
  const [insights, setInsights] = useState<Insights | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  async function fetchInsights() {
    setLoading(true);
    setError(null);
    try {
      const res = await fetch("/api/insights", { method: "POST" });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error ?? "Could not generate insights.");
      setInsights(data.insights as Insights);
    } catch (err) {
      setError(err instanceof Error ? err.message : "Something went wrong.");
    } finally {
      setLoading(false);
    }
  }

  return (
    <section className="card full" aria-labelledby="insights-heading">
      <h2 id="insights-heading">Your personalized plan</h2>
      <p className="muted">
        Get smart, context-aware actions based on what you&apos;ve actually logged.
      </p>
      <button
        type="button"
        className="primary insights-btn"
        onClick={fetchInsights}
        disabled={loading}
      >
        {loading ? "Thinking…" : insights ? "Refresh insights" : "Get insights"}
      </button>

      <div role="status" aria-live="polite">
        {error && (
          <p className="status error">{error}</p>
        )}

        {insights && (
          <div className="insights-result">
            <p className="insight-message">{insights.message}</p>
            <ul className="recs">
              {insights.recommendations.map((rec) => (
                <li key={rec.title}>
                  <h3>{rec.title}</h3>
                  <p>{rec.detail}</p>
                  {typeof rec.estimatedSavingKg === "number" && (
                    <span className="saving">
                      ↓ saves ~{rec.estimatedSavingKg} kg CO₂e
                    </span>
                  )}
                </li>
              ))}
            </ul>
            <p className="muted attribution">
              Narrative generated by {insights.generatedBy === "groq" ? "Groq AI" : "the rules engine"}.
            </p>
          </div>
        )}
      </div>
    </section>
  );
}
